"""
Data augmentation for synthetic time series datasets.

Each batch used for training contains N/4 originals generated by the DAG
generator and 3N/4 augmented copies.  augment_dataset() applies the full
augmentation pipeline to one original and returns an independently augmented
copy (not in-place).

Pipeline (applied to train + test concatenated, then split back)
----------------------------------------------------------------
  1. Feature channel permutation
  2. Class label permutation
  3. Per-feature value transform: none / log / exp / squash / KDI / Kumaraswamy
     (accidental NaN/Inf sanitised before step 4)
  4. Temporal granularity transform (dataset-level):
       identity (75%) | pooling mean/max/min/global (25%, global most likely) | step-repeat upsampling (10%)
  4b. Feature channel permutation (so global pooling order isn't always mean/max/min)
  5. Per-feature independent missing values (NaN, low probability)
  6. Re-pad T to a multiple of group_size (right zero-pad)

Transform details
-----------------
  none     — identity
  log      — sign(x) * log(|x| + 1)
  exp      — sign(x) * (exp(|x|) − 1), |x| clipped to 10 before expm1
  squash   — robust scaling (median / IQR) + soft clip to [−B, B]
  kdi      — Kernel Density Integral; alpha ~ LogNormal(0, 0.8²) ∈ [0.05, 10]
  kuma     — Kumaraswamy CDF warp; a, b ~ LogNormal(0, 0.7²) ∈ [0.2, 5]

For KDI/Kumaraswamy the parameters are sampled per feature channel.
Statistics are computed on the FULL dataset (train + test pooled).

Run as a script to generate diagnostic visualizations:
  python 02_synthetic_data/augmentation.py
  python 02_synthetic_data/augmentation.py --n-series 6 --seed 42
"""

from __future__ import annotations

import numpy as np

from hyperparameters import AugmentationHyperparameters

# ─────────────────────────────────────────────────────────────────────────────
# Module-level defaults derived from AugmentationHyperparameters
# ─────────────────────────────────────────────────────────────────────────────

_DEFAULT_AUG_HP = AugmentationHyperparameters()

_TRANSFORM_CHOICES = list(_DEFAULT_AUG_HP.transform_choices)
_weights_raw = np.array([
    _DEFAULT_AUG_HP.transform_none_weight if c == "none" else 1.0
    for c in _TRANSFORM_CHOICES
])
_TRANSFORM_WEIGHTS = _weights_raw / _weights_raw.sum()

_TEMPORAL_PROBS = np.array(_DEFAULT_AUG_HP.temporal_probs, dtype=float)
_TEMPORAL_PROBS = _TEMPORAL_PROBS / _TEMPORAL_PROBS.sum()   # identity / pool / interp

_POOL_TYPE_PROBS = np.array(_DEFAULT_AUG_HP.pool_type_probs, dtype=float)

_MISSING_FEATURE_PROB = _DEFAULT_AUG_HP.missing_feature_prob


# ─────────────────────────────────────────────────────────────────────────────
# Per-feature value transforms
# ─────────────────────────────────────────────────────────────────────────────

def _safe_log(x: np.ndarray) -> np.ndarray:
    return np.sign(x) * np.log1p(np.abs(x))


def _safe_exp(x: np.ndarray) -> np.ndarray:
    return np.sign(x) * np.expm1(np.clip(np.abs(x), 0.0, 10.0))


def _squash(X_block: np.ndarray, max_abs: float = 3.0) -> np.ndarray:
    """Robust scaling (median / IQR) + soft clip.  X_block: (n, T)."""
    X = X_block.copy().astype(np.float64)
    vals = X.ravel()
    finite = vals[np.isfinite(vals)]
    if len(finite) == 0:
        return X.astype(np.float32)
    median = np.median(finite)
    q_lo, q_hi = np.percentile(finite, 25.0), np.percentile(finite, 75.0)
    if q_hi != q_lo:
        scale = 1.0 / (q_hi - q_lo)
    else:
        vmin, vmax = np.min(finite), np.max(finite)
        if vmax != vmin:
            scale = 2.0 / (vmax - vmin)
        else:
            return np.zeros_like(X, dtype=np.float32)
    X = (X - median) * scale
    X = X / np.sqrt(1.0 + (X / max_abs) ** 2)
    return X.astype(np.float32)


def _kdi(X_block: np.ndarray, alpha: float, output_dist: str) -> np.ndarray:
    """KDI transform.  X_block: (n, T).  Fit on all data, transform per column."""
    T = X_block.shape[1]
    X = X_block.copy()
    try:
        from tabpfn.preprocessing.steps.kdi_transformer import KDITransformerWithNaN

        all_vals = X.ravel().reshape(-1, 1).astype(np.float64)
        kdi = KDITransformerWithNaN(alpha=alpha, output_distribution=output_dist)
        kdi.fit(all_vals)
        for t in range(T):
            col = X[:, t : t + 1].astype(np.float64)
            out = kdi.transform(col).astype(np.float32)
            if np.all(np.isfinite(out)):
                X[:, t : t + 1] = out
    except Exception:
        pass
    return X.astype(np.float32)


def _kuma(X_block: np.ndarray, a: float, b: float) -> np.ndarray:
    """Kumaraswamy CDF warp.  X_block: (n, T)."""
    X = X_block.copy().astype(np.float64)
    vals = X.ravel()
    finite = vals[np.isfinite(vals)]
    if len(finite) == 0:
        return X.astype(np.float32)
    xmin, xmax = np.min(finite), np.max(finite)
    if xmax <= xmin:
        return X.astype(np.float32)
    X_norm = np.clip((X - xmin) / (xmax - xmin), 1e-12, 1.0 - 1e-12)
    X_warp = 1.0 - (1.0 - np.power(X_norm, a)) ** b
    X_out = X_warp * (xmax - xmin) + xmin
    return X_out.astype(np.float32) if np.all(np.isfinite(X_out)) else X_block.astype(np.float32)


# ─────────────────────────────────────────────────────────────────────────────
# Temporal granularity transforms
# ─────────────────────────────────────────────────────────────────────────────

def _pool_channels(X_3d: np.ndarray, K: int, S: int, pool_type: str) -> np.ndarray:
    """Sliding-window pooling: (n, m, T) → (n, m_out, T_new).

    pool_type 'mean' / 'max' / 'min' → m_out = m
    pool_type 'global'               → m_out = 3*m  (min + max + mean)
    """
    from numpy.lib.stride_tricks import sliding_window_view

    windows = sliding_window_view(X_3d, K, axis=2)[:, :, ::S, :]   # (n, m, T_new, K)
    if pool_type == "mean":
        return windows.mean(axis=3).astype(np.float32)
    elif pool_type == "max":
        return windows.max(axis=3).astype(np.float32)
    elif pool_type == "min":
        return windows.min(axis=3).astype(np.float32)
    else:  # global: min + max + mean  →  m_out = 3*m
        return np.concatenate(
            [windows.min(axis=3), windows.max(axis=3), windows.mean(axis=3)], axis=1
        ).astype(np.float32)


def _repeat_channels(X_3d: np.ndarray, n: int) -> np.ndarray:
    """Step-repeat interpolation: each timestep is repeated n times.

    (n_samples, m, T) → (n_samples, m, T*n).
    The series appears to change more slowly: values stay constant for n steps
    before moving to the next original timestep.
    """
    return np.repeat(X_3d, n, axis=2).astype(np.float32)


def _temporal_granularity(
    X_3d: np.ndarray, m: int, T: int, rng,
    max_T: int = 2000, max_m: int = 200, max_m_times_T: int = 2000,
) -> tuple[np.ndarray, int, int]:
    """Apply a random temporal granularity change.  Returns (X_out, T_new, m_new)."""
    mode = rng.choice(["identity", "pooling", "interp"], p=_TEMPORAL_PROBS)

    if mode == "identity":
        return X_3d, T, m

    if mode == "pooling":
        K = int(rng.choice([2, 3, 4, 5]))
        S = int(rng.randint(1, K + 1))
        T_new = (T - K) // S + 1
        if T_new < 8:
            return X_3d, T, m

        pool_type = rng.choice(["mean", "max", "min", "global"], p=_POOL_TYPE_PROBS)
        m_new = 3 * m if pool_type == "global" else m

        if m_new > max_m or m_new * T_new > max_m_times_T:
            if pool_type == "global":
                pool_type = rng.choice(["mean", "max", "min"])
                m_new = m
            if m_new * T_new > max_m_times_T:
                return X_3d, T, m

        return _pool_channels(X_3d, K, S, pool_type), T_new, m_new

    else:  # step-repeat upsampling
        # Sample repetition factor n (>= 2).  Only apply when m * T * n <= max_m_times_T.
        n_max = max_m_times_T // max(m * T, 1)
        if n_max < 2:
            return X_3d, T, m
        n = int(rng.randint(2, min(n_max, 8) + 1))   # cap at 8× to avoid extreme upsampling
        T_new = T * n
        return _repeat_channels(X_3d, n), T_new, m


def _apply_missings(
    X_3d: np.ndarray, m: int, T: int, rng,
    missing_feature_prob: float = _MISSING_FEATURE_PROB,
) -> np.ndarray:
    """Per-feature independent missing values (NaN), log-uniform rate."""
    X_out = X_3d.copy()
    n = X_3d.shape[0]
    for j in range(m):
        if rng.random() < missing_feature_prob:
            r = float(np.exp(rng.uniform(np.log(0.01), np.log(0.3))))
            mask = rng.random(size=(n, T)) < r
            X_out[:, j, :][mask] = np.nan
    return X_out


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def augment_dataset(
    data: dict,
    rng: np.random.RandomState,
    max_T: int = _DEFAULT_AUG_HP.aug_max_T,
    max_m: int = _DEFAULT_AUG_HP.aug_max_m,
    max_m_times_T: int = _DEFAULT_AUG_HP.aug_max_m_times_T,
    group_size: int = 8,
) -> dict:
    """Create one augmented copy of a synthetic dataset dict.

    The input dict must have keys: X_train, X_test, y_train, y_test,
    n_classes, n_features_orig, T.  Returns a new dict with the same keys
    plus '_augmented': True.
    """
    m = data["n_features_orig"]
    T = data["T"]
    n_classes = data["n_classes"]
    n_tr = data["X_train"].shape[0]

    X_all_3d = np.concatenate(
        [data["X_train"].reshape(-1, m, T), data["X_test"].reshape(-1, m, T)], axis=0
    ).copy()
    n_all = X_all_3d.shape[0]
    y_train = data["y_train"].copy()
    y_test = data["y_test"].copy()

    # 1. Feature channel permutation
    feat_perm = rng.permutation(m)
    X_all_3d = X_all_3d[:, feat_perm, :]

    # 2. Class label permutation
    class_perm = rng.permutation(n_classes)
    y_train = class_perm[y_train]
    y_test = class_perm[y_test]

    # 3. Per-feature value transform
    X_all = X_all_3d.reshape(n_all, m * T)
    for j in range(m):
        s, e = j * T, j * T + T
        transform = rng.choice(_TRANSFORM_CHOICES, p=_TRANSFORM_WEIGHTS)
        if transform == "none":
            continue
        elif transform == "log":
            X_all[:, s:e] = _safe_log(X_all[:, s:e])
        elif transform == "exp":
            X_all[:, s:e] = _safe_exp(X_all[:, s:e])
        elif transform == "squash":
            X_all[:, s:e] = _squash(X_all[:, s:e])
        elif transform == "kdi":
            alpha = float(np.clip(np.exp(rng.randn() * 0.8), 0.05, 10.0))
            out_dist = rng.choice(["normal", "uniform"])
            X_all[:, s:e] = _kdi(X_all[:, s:e], alpha, out_dist)
        elif transform == "kuma":
            a = float(np.clip(np.exp(rng.randn() * 0.7), 0.2, 5.0))
            b = float(np.clip(np.exp(rng.randn() * 0.7), 0.2, 5.0))
            X_all[:, s:e] = _kuma(X_all[:, s:e], a, b)

    # Sanitise accidental NaN/Inf from value transforms (before adding intentional NaN)
    X_all = np.nan_to_num(X_all, nan=0.0, posinf=1e6, neginf=-1e6)
    X_all = np.clip(X_all, -1e6, 1e6).astype(np.float32)
    X_all_3d = X_all.reshape(n_all, m, T)

    # 4. Temporal granularity transform (dataset-level)
    X_all_3d, T_new, m_new = _temporal_granularity(
        X_all_3d, m, T, rng, max_T=max_T, max_m=max_m, max_m_times_T=max_m_times_T
    )

    # 4b. Permute feature channels after temporal granularity (so global pooling
    #     isn't always mean, max, min in the same order)
    channel_perm = rng.permutation(m_new)
    X_all_3d = X_all_3d[:, channel_perm, :]

    # 5. Missing values (intentional NaN, per-feature)
    X_all_3d = _apply_missings(X_all_3d, m_new, T_new, rng)

    # 6. Re-pad T_new to multiple of group_size
    remainder = T_new % group_size
    if remainder == 0:
        T_padded = T_new
        X_flat = X_all_3d.reshape(n_all, m_new * T_padded)
    else:
        pad_t = group_size - remainder
        T_padded = T_new + pad_t
        X_3d_padded = np.pad(X_all_3d, ((0, 0), (0, 0), (0, pad_t)), constant_values=0.0)
        X_flat = X_3d_padded.reshape(n_all, m_new * T_padded).astype(np.float32)

    return {
        "X_train": X_flat[:n_tr],
        "X_test": X_flat[n_tr:],
        "y_train": y_train.astype(np.int64),
        "y_test": y_test.astype(np.int64),
        "n_classes": n_classes,
        "n_features": X_flat.shape[1],
        "n_features_orig": m_new,
        "T": T_padded,
        "n_samples": data["n_samples"],
        "_augmented": True,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Diagnostic visualizations (run as script)
# ─────────────────────────────────────────────────────────────────────────────

def _viz_transforms(out_dir, n_series: int = 6, seed: int = 42):
    """Plot each value transform on one series per generator seed.

    Columns: Original | Log | Exp | Squash | KDI (3 α) | Kuma (3 params)
    One row per generator seed.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import sys
    import warnings
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).parent))
    sys.path.insert(0, str(Path(__file__).parent.parent / "00_TabPFN" / "src"))
    from generator import DatasetGenerator
    from hyperparameters import GeneratorHyperparameters

    hp = GeneratorHyperparameters()
    kdi_alphas = [0.3, 1.0, 3.0]
    kuma_params = [(0.5, 0.5), (2.0, 0.5), (0.5, 2.0)]

    col_specs = (
        [("Original", "#2196F3"), ("Log", "#4CAF50"), ("Exp", "#FF5722"), ("Squash", "#607D8B")]
        + [(f"KDI α={a}", c) for a, c in zip(kdi_alphas, ["#9C27B0", "#FF9800", "#795548"])]
        + [(f"Kuma({a},{b})", c)
           for (a, b), c in zip(kuma_params, ["#E91E63", "#00BCD4", "#8BC34A"])]
    )
    n_cols = len(col_specs)

    fig, axes = plt.subplots(n_series, n_cols, figsize=(3.0 * n_cols, 2.6 * n_series), squeeze=False)
    for c, (title, _) in enumerate(col_specs):
        axes[0, c].set_title(title, fontsize=9, fontweight="bold")

    row, s = 0, seed
    while row < n_series:
        s += 1
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", RuntimeWarning)
                ds = DatasetGenerator(seed=s, hp=hp).generate_dataset()
        except Exception:
            continue
        if ds is None or ds["X_train"].shape[0] == 0 or ds["X_train"].shape[2] < 5:
            continue

        series = ds["X_train"][0, 0, :].astype(np.float32)
        t_axis = np.arange(len(series))
        axes[row, 0].set_ylabel(f"seed {s}\nT={ds['T']}, m={ds['n_features']}", fontsize=7)

        def _kdi_1d(x, alpha):
            try:
                from tabpfn.preprocessing.steps.kdi_transformer import KDITransformerWithNaN
                kdi = KDITransformerWithNaN(alpha=alpha, output_distribution="normal")
                col = x.reshape(-1, 1).astype(np.float64)
                kdi.fit(col)
                out = kdi.transform(col).ravel().astype(np.float32)
                return out if np.all(np.isfinite(out)) else x
            except Exception:
                return x

        def _kuma_1d(x, a, b):
            xmin, xmax = x.min(), x.max()
            if xmax <= xmin:
                return x
            xn = np.clip((x - xmin) / (xmax - xmin), 1e-12, 1 - 1e-12)
            return (1.0 - (1.0 - xn ** a) ** b) * (xmax - xmin) + xmin

        transforms = [
            series,
            _safe_log(series),
            _safe_exp(series),
            _squash(series.reshape(1, -1)).ravel(),
        ] + [_kdi_1d(series, a) for a in kdi_alphas] + [_kuma_1d(series, a, b) for a, b in kuma_params]

        for c, ((_, color), data) in enumerate(zip(col_specs, transforms)):
            axes[row, c].plot(t_axis, data, color=color, linewidth=0.8)
            axes[row, c].tick_params(labelsize=6)
            if row < n_series - 1:
                axes[row, c].set_xticklabels([])

        row += 1

    plt.suptitle("Value transforms applied to one feature channel per generator seed",
                 fontsize=12, fontweight="bold", y=1.01)
    plt.tight_layout()
    out_path = out_dir / "value_transforms.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")


def _viz_temporal(out_dir, n_examples: int = 5, seed: int = 0):
    """Show a dataset before and after each temporal granularity mode.

    One row per generator seed, columns:
      Original | Pooling mean | Pooling max | Pooling min | Pooling global | Step-repeat ×2
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import sys
    import warnings
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).parent))
    sys.path.insert(0, str(Path(__file__).parent.parent / "00_TabPFN" / "src"))
    from generator import DatasetGenerator
    from hyperparameters import GeneratorHyperparameters

    hp = GeneratorHyperparameters()
    cols = [
        ("Original", "#2196F3"),
        ("Pool mean K=4 S=2", "#4CAF50"),
        ("Pool max K=4 S=2", "#FF9800"),
        ("Pool min K=4 S=2", "#00BCD4"),
        ("Pool global K=4 S=2", "#9C27B0"),
        ("Step-repeat ×2", "#E91E63"),
    ]
    n_cols = len(cols)

    fig, axes = plt.subplots(n_examples, n_cols, figsize=(3.5 * n_cols, 2.6 * n_examples), squeeze=False)
    for c, (title, _) in enumerate(cols):
        axes[0, c].set_title(title, fontsize=9, fontweight="bold")

    row, s = 0, seed
    while row < n_examples:
        s += 1
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", RuntimeWarning)
                ds = DatasetGenerator(seed=s, hp=hp).generate_dataset()
        except Exception:
            continue
        if ds is None or ds["X_train"].shape[0] == 0 or ds["X_train"].shape[2] < 8:
            continue

        X_3d = ds["X_train"][:1].astype(np.float32)   # (1, m, T)
        series_orig = X_3d[0, 0]
        T = series_orig.shape[0]
        axes[row, 0].set_ylabel(f"seed {s}\nT={T}, m={ds['n_features']}", fontsize=7)

        K, S = 4, 2
        variants = [series_orig]
        for pool_type in ("mean", "max", "min", "global"):
            pooled = _pool_channels(X_3d, K, S, pool_type)
            variants.append(pooled[0, 0])   # first channel (global triples channels, still take [0,0])
        variants.append(_repeat_channels(X_3d, 2)[0, 0])

        for c, ((_, color), data) in enumerate(zip(cols, variants)):
            axes[row, c].plot(np.linspace(0, T - 1, len(data)), data, color=color, linewidth=0.8)
            axes[row, c].tick_params(labelsize=6)
            axes[row, c].set_xlim(0, T - 1)
            if row < n_examples - 1:
                axes[row, c].set_xticklabels([])

        row += 1

    plt.suptitle("Temporal granularity transforms (first feature channel, first sample)",
                 fontsize=12, fontweight="bold", y=1.01)
    plt.tight_layout()
    out_path = out_dir / "temporal_transforms.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")


def _viz_augmentation_pipeline(out_dir, n_examples: int = 4, seed: int = 7):
    """Show original vs augmented dataset side by side.

    Each row: one dataset.  Columns show train class distribution as a
    multi-line plot (one line per class, first feature channel) before and
    after augment_dataset().
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import sys
    import warnings
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).parent))
    sys.path.insert(0, str(Path(__file__).parent.parent / "00_TabPFN" / "src"))
    from generator import DatasetGenerator
    from hyperparameters import GeneratorHyperparameters

    hp = GeneratorHyperparameters()
    fig, axes = plt.subplots(n_examples, 2, figsize=(12, 3 * n_examples), squeeze=False)
    axes[0, 0].set_title("Original", fontsize=11, fontweight="bold")
    axes[0, 1].set_title("After augment_dataset()", fontsize=11, fontweight="bold")

    rng_aug = np.random.RandomState(seed + 100)
    colors = ["#2196F3", "#E91E63", "#4CAF50", "#FF9800", "#9C27B0", "#795548", "#00BCD4", "#607D8B"]

    row, s = 0, seed
    while row < n_examples:
        s += 1
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", RuntimeWarning)
                raw = DatasetGenerator(seed=s, hp=hp).generate_dataset()
        except Exception:
            continue
        if raw is None or raw["X_train"].shape[0] < 4 or raw["X_train"].shape[2] < 5:
            continue

        # Adapt raw generator dict (3D X, no n_features_orig) to augment_dataset format
        m_orig = raw["n_features"]
        T_orig = raw["T"]
        X_tr_3d = raw["X_train"]   # (n_train, m, T)
        X_te_3d = raw["X_test"]
        ds = {
            "X_train": X_tr_3d.reshape(X_tr_3d.shape[0], -1).astype(np.float32),
            "X_test":  X_te_3d.reshape(X_te_3d.shape[0], -1).astype(np.float32),
            "y_train": raw["y_train"].astype(np.int64),
            "y_test":  raw["y_test"].astype(np.int64),
            "n_classes": raw["n_classes"],
            "n_features_orig": m_orig,
            "T": T_orig,
            "n_samples": raw["n_samples"],
        }

        aug = augment_dataset(ds, rng_aug)
        m_aug, T_aug = aug["n_features_orig"], aug["T"]

        def _plot_panel(ax, X_flat, y, m, T, label):
            X_3d = X_flat.reshape(-1, m, T)
            for cls in np.unique(y):
                idx = np.where(y == cls)[0][:8]
                for i in idx:
                    ax.plot(X_3d[i, 0], color=colors[cls % len(colors)], alpha=0.4, linewidth=0.7)
            ax.set_ylabel(label, fontsize=7)
            ax.tick_params(labelsize=6)

        _plot_panel(axes[row, 0], ds["X_train"], ds["y_train"], m_orig, T_orig,
                    f"seed {s}\nm={m_orig}, T={T_orig}\ncls={ds['n_classes']}")
        _plot_panel(axes[row, 1], aug["X_train"], aug["y_train"], m_aug, T_aug,
                    f"m={m_aug}, T={T_aug}")

        row += 1

    plt.suptitle("Augmentation pipeline: original vs augmented (colored by class)",
                 fontsize=12, fontweight="bold", y=1.01)
    plt.tight_layout()
    out_path = out_dir / "augmentation_pipeline.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")


if __name__ == "__main__":
    import argparse
    from pathlib import Path

    parser = argparse.ArgumentParser(description="Generate augmentation diagnostic visualizations.")
    parser.add_argument("--n-series", type=int, default=6,
                        help="Rows in the transforms plot (default 6)")
    parser.add_argument("--seed", type=int, default=42, help="Base random seed")
    parser.add_argument("--out-dir", type=str, default=None,
                        help="Output directory (default: 02_synthetic_data/visualizations/augmentation/)")
    args = parser.parse_args()

    out_dir = Path(args.out_dir) if args.out_dir else Path(__file__).parent / "visualizations" / "augmentation"
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"Writing visualizations to {out_dir}/")

    print("1/3  Value transforms per series...")
    _viz_transforms(out_dir, n_series=args.n_series, seed=args.seed)

    print("2/3  Temporal granularity transforms...")
    _viz_temporal(out_dir, n_examples=args.n_series, seed=args.seed)

    print("3/3  Full augmentation pipeline (original vs augmented)...")
    _viz_augmentation_pipeline(out_dir, n_examples=args.n_series, seed=args.seed)

    print("Done.")
